# Use a lightweight Nginx image
FROM nginx:stable-alpine

# Copy static assets from the current directory to the Nginx public folder
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# The default command for Nginx is to start the server, but we make it explicit
CMD ["nginx", "-g", "daemon off;"]
